// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentMethod struct {
	ID        pgtype.UUID `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	Name      string      `json:"name"`
	CreatedAt int32       `json:"created_at"`
	UpdatedAt int32       `json:"updated_at"`
}

type Subscription struct {
	ID              pgtype.UUID `json:"id"`
	UserID          pgtype.UUID `json:"user_id"`
	ServiceName     string      `json:"service_name"`
	Amount          int32       `json:"amount"`
	BillingCycle    string      `json:"billing_cycle"`
	BaseDate        int32       `json:"base_date"`
	PaymentMethodID pgtype.UUID `json:"payment_method_id"`
	Memo            *string     `json:"memo"`
	CreatedAt       int32       `json:"created_at"`
	UpdatedAt       int32       `json:"updated_at"`
}

type User struct {
	ID                pgtype.UUID `json:"id"`
	Email             string      `json:"email"`
	Name              string      `json:"name"`
	Provider          string      `json:"provider"`
	ProviderAccountID string      `json:"provider_account_id"`
	Thumbnail         *string     `json:"thumbnail"`
	CreatedAt         int32       `json:"created_at"`
	UpdatedAt         int32       `json:"updated_at"`
}
