FROM golang:1.26.0

WORKDIR /app

# Install Air for hot reload
RUN go install github.com/air-verse/air@latest

# Install sqlc for code generation
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

# Pre-fetch modules for faster startup
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
