FROM golang:1.26.5

WORKDIR /app

# Install aqua (declarative CLI version manager) for dev tools
ENV AQUA_ROOT_DIR=/root/.local/share/aquaproj-aqua
ENV PATH="${AQUA_ROOT_DIR}/bin:${PATH}"
RUN curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v4.0.5/aqua-installer | bash

# Install dev tools defined in aqua.yaml
# (air, sqlc, golangci-lint, oapi-codegen, migrate)
COPY aqua.yaml ./
RUN aqua install --all

# Pre-fetch modules for faster startup
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
