// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/adapter/gateway/db/sqlc/generated/querier.go
//
// Generated by this command:
//
//	mockgen -source=./internal/adapter/gateway/db/sqlc/generated/querier.go -destination=./internal/adapter/gateway/db/sqlc/mock/mock_querier.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	generated "github.com/atsushi-h/subsq/backend/internal/adapter/gateway/db/sqlc/generated"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CountSubscriptionsByPaymentMethodID mocks base method.
func (m *MockQuerier) CountSubscriptionsByPaymentMethodID(ctx context.Context, paymentMethodID pgtype.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSubscriptionsByPaymentMethodID", ctx, paymentMethodID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSubscriptionsByPaymentMethodID indicates an expected call of CountSubscriptionsByPaymentMethodID.
func (mr *MockQuerierMockRecorder) CountSubscriptionsByPaymentMethodID(ctx, paymentMethodID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSubscriptionsByPaymentMethodID", reflect.TypeOf((*MockQuerier)(nil).CountSubscriptionsByPaymentMethodID), ctx, paymentMethodID)
}

// CountSubscriptionsByPaymentMethodIDs mocks base method.
func (m *MockQuerier) CountSubscriptionsByPaymentMethodIDs(ctx context.Context, dollar_1 []pgtype.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSubscriptionsByPaymentMethodIDs", ctx, dollar_1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSubscriptionsByPaymentMethodIDs indicates an expected call of CountSubscriptionsByPaymentMethodIDs.
func (mr *MockQuerierMockRecorder) CountSubscriptionsByPaymentMethodIDs(ctx, dollar_1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSubscriptionsByPaymentMethodIDs", reflect.TypeOf((*MockQuerier)(nil).CountSubscriptionsByPaymentMethodIDs), ctx, dollar_1)
}

// CreatePaymentMethod mocks base method.
func (m *MockQuerier) CreatePaymentMethod(ctx context.Context, arg *generated.CreatePaymentMethodParams) (*generated.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentMethod", ctx, arg)
	ret0, _ := ret[0].(*generated.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePaymentMethod indicates an expected call of CreatePaymentMethod.
func (mr *MockQuerierMockRecorder) CreatePaymentMethod(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentMethod", reflect.TypeOf((*MockQuerier)(nil).CreatePaymentMethod), ctx, arg)
}

// CreateSubscription mocks base method.
func (m *MockQuerier) CreateSubscription(ctx context.Context, arg *generated.CreateSubscriptionParams) (*generated.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, arg)
	ret0, _ := ret[0].(*generated.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockQuerierMockRecorder) CreateSubscription(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockQuerier)(nil).CreateSubscription), ctx, arg)
}

// DeletePaymentMethod mocks base method.
func (m *MockQuerier) DeletePaymentMethod(ctx context.Context, arg *generated.DeletePaymentMethodParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePaymentMethod", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePaymentMethod indicates an expected call of DeletePaymentMethod.
func (mr *MockQuerierMockRecorder) DeletePaymentMethod(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePaymentMethod", reflect.TypeOf((*MockQuerier)(nil).DeletePaymentMethod), ctx, arg)
}

// DeletePaymentMethods mocks base method.
func (m *MockQuerier) DeletePaymentMethods(ctx context.Context, arg *generated.DeletePaymentMethodsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePaymentMethods", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePaymentMethods indicates an expected call of DeletePaymentMethods.
func (mr *MockQuerierMockRecorder) DeletePaymentMethods(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePaymentMethods", reflect.TypeOf((*MockQuerier)(nil).DeletePaymentMethods), ctx, arg)
}

// DeleteSubscription mocks base method.
func (m *MockQuerier) DeleteSubscription(ctx context.Context, arg *generated.DeleteSubscriptionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscription", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockQuerierMockRecorder) DeleteSubscription(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscription", reflect.TypeOf((*MockQuerier)(nil).DeleteSubscription), ctx, arg)
}

// DeleteSubscriptions mocks base method.
func (m *MockQuerier) DeleteSubscriptions(ctx context.Context, arg *generated.DeleteSubscriptionsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscriptions", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscriptions indicates an expected call of DeleteSubscriptions.
func (mr *MockQuerierMockRecorder) DeleteSubscriptions(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscriptions", reflect.TypeOf((*MockQuerier)(nil).DeleteSubscriptions), ctx, arg)
}

// DeleteUser mocks base method.
func (m *MockQuerier) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockQuerierMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockQuerier)(nil).DeleteUser), ctx, id)
}

// FindPaymentMethodsByIDs mocks base method.
func (m *MockQuerier) FindPaymentMethodsByIDs(ctx context.Context, arg *generated.FindPaymentMethodsByIDsParams) ([]*generated.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPaymentMethodsByIDs", ctx, arg)
	ret0, _ := ret[0].([]*generated.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPaymentMethodsByIDs indicates an expected call of FindPaymentMethodsByIDs.
func (mr *MockQuerierMockRecorder) FindPaymentMethodsByIDs(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPaymentMethodsByIDs", reflect.TypeOf((*MockQuerier)(nil).FindPaymentMethodsByIDs), ctx, arg)
}

// FindSubscriptionsByIDs mocks base method.
func (m *MockQuerier) FindSubscriptionsByIDs(ctx context.Context, arg *generated.FindSubscriptionsByIDsParams) ([]*generated.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSubscriptionsByIDs", ctx, arg)
	ret0, _ := ret[0].([]*generated.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSubscriptionsByIDs indicates an expected call of FindSubscriptionsByIDs.
func (mr *MockQuerierMockRecorder) FindSubscriptionsByIDs(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSubscriptionsByIDs", reflect.TypeOf((*MockQuerier)(nil).FindSubscriptionsByIDs), ctx, arg)
}

// FindUserByID mocks base method.
func (m *MockQuerier) FindUserByID(ctx context.Context, id pgtype.UUID) (*generated.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByID", ctx, id)
	ret0, _ := ret[0].(*generated.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByID indicates an expected call of FindUserByID.
func (mr *MockQuerierMockRecorder) FindUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByID", reflect.TypeOf((*MockQuerier)(nil).FindUserByID), ctx, id)
}

// GetPaymentMethodByID mocks base method.
func (m *MockQuerier) GetPaymentMethodByID(ctx context.Context, arg *generated.GetPaymentMethodByIDParams) (*generated.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentMethodByID", ctx, arg)
	ret0, _ := ret[0].(*generated.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentMethodByID indicates an expected call of GetPaymentMethodByID.
func (mr *MockQuerierMockRecorder) GetPaymentMethodByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentMethodByID", reflect.TypeOf((*MockQuerier)(nil).GetPaymentMethodByID), ctx, arg)
}

// GetSubscriptionByID mocks base method.
func (m *MockQuerier) GetSubscriptionByID(ctx context.Context, arg *generated.GetSubscriptionByIDParams) (*generated.GetSubscriptionByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionByID", ctx, arg)
	ret0, _ := ret[0].(*generated.GetSubscriptionByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionByID indicates an expected call of GetSubscriptionByID.
func (mr *MockQuerierMockRecorder) GetSubscriptionByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionByID", reflect.TypeOf((*MockQuerier)(nil).GetSubscriptionByID), ctx, arg)
}

// ListPaymentMethodsByUserID mocks base method.
func (m *MockQuerier) ListPaymentMethodsByUserID(ctx context.Context, userID pgtype.UUID) ([]*generated.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPaymentMethodsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*generated.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPaymentMethodsByUserID indicates an expected call of ListPaymentMethodsByUserID.
func (mr *MockQuerierMockRecorder) ListPaymentMethodsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaymentMethodsByUserID", reflect.TypeOf((*MockQuerier)(nil).ListPaymentMethodsByUserID), ctx, userID)
}

// ListPaymentMethodsWithCountByUserID mocks base method.
func (m *MockQuerier) ListPaymentMethodsWithCountByUserID(ctx context.Context, userID pgtype.UUID) ([]*generated.ListPaymentMethodsWithCountByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPaymentMethodsWithCountByUserID", ctx, userID)
	ret0, _ := ret[0].([]*generated.ListPaymentMethodsWithCountByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPaymentMethodsWithCountByUserID indicates an expected call of ListPaymentMethodsWithCountByUserID.
func (mr *MockQuerierMockRecorder) ListPaymentMethodsWithCountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaymentMethodsWithCountByUserID", reflect.TypeOf((*MockQuerier)(nil).ListPaymentMethodsWithCountByUserID), ctx, userID)
}

// ListSubscriptionsByUserID mocks base method.
func (m *MockQuerier) ListSubscriptionsByUserID(ctx context.Context, userID pgtype.UUID) ([]*generated.ListSubscriptionsByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubscriptionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*generated.ListSubscriptionsByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubscriptionsByUserID indicates an expected call of ListSubscriptionsByUserID.
func (mr *MockQuerierMockRecorder) ListSubscriptionsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubscriptionsByUserID", reflect.TypeOf((*MockQuerier)(nil).ListSubscriptionsByUserID), ctx, userID)
}

// UpdatePaymentMethod mocks base method.
func (m *MockQuerier) UpdatePaymentMethod(ctx context.Context, arg *generated.UpdatePaymentMethodParams) (*generated.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentMethod", ctx, arg)
	ret0, _ := ret[0].(*generated.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePaymentMethod indicates an expected call of UpdatePaymentMethod.
func (mr *MockQuerierMockRecorder) UpdatePaymentMethod(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentMethod", reflect.TypeOf((*MockQuerier)(nil).UpdatePaymentMethod), ctx, arg)
}

// UpdateSubscription mocks base method.
func (m *MockQuerier) UpdateSubscription(ctx context.Context, arg *generated.UpdateSubscriptionParams) (*generated.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscription", ctx, arg)
	ret0, _ := ret[0].(*generated.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubscription indicates an expected call of UpdateSubscription.
func (mr *MockQuerierMockRecorder) UpdateSubscription(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscription", reflect.TypeOf((*MockQuerier)(nil).UpdateSubscription), ctx, arg)
}

// UpsertUser mocks base method.
func (m *MockQuerier) UpsertUser(ctx context.Context, arg *generated.UpsertUserParams) (*generated.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUser", ctx, arg)
	ret0, _ := ret[0].(*generated.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUser indicates an expected call of UpsertUser.
func (mr *MockQuerierMockRecorder) UpsertUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockQuerier)(nil).UpsertUser), ctx, arg)
}
