// Code generated by MockGen. DO NOT EDIT.
// Source: payment_method_port.go
//
// Generated by this command:
//
//	mockgen -source=payment_method_port.go -destination=../usecase/mock/mock_payment_method_usecase.go -package=mockusecase
//

// Package mockusecase is a generated GoMock package.
package mockusecase

import (
	context "context"
	reflect "reflect"

	payment_method "github.com/atsushi-h/subsq/backend/internal/domain/payment_method"
	port "github.com/atsushi-h/subsq/backend/internal/port"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentMethodInputPort is a mock of PaymentMethodInputPort interface.
type MockPaymentMethodInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentMethodInputPortMockRecorder
	isgomock struct{}
}

// MockPaymentMethodInputPortMockRecorder is the mock recorder for MockPaymentMethodInputPort.
type MockPaymentMethodInputPortMockRecorder struct {
	mock *MockPaymentMethodInputPort
}

// NewMockPaymentMethodInputPort creates a new mock instance.
func NewMockPaymentMethodInputPort(ctrl *gomock.Controller) *MockPaymentMethodInputPort {
	mock := &MockPaymentMethodInputPort{ctrl: ctrl}
	mock.recorder = &MockPaymentMethodInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentMethodInputPort) EXPECT() *MockPaymentMethodInputPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentMethodInputPort) Create(ctx context.Context, userID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPaymentMethodInputPortMockRecorder) Create(ctx, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentMethodInputPort)(nil).Create), ctx, userID, name)
}

// Delete mocks base method.
func (m *MockPaymentMethodInputPort) Delete(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPaymentMethodInputPortMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPaymentMethodInputPort)(nil).Delete), ctx, id, userID)
}

// DeleteMany mocks base method.
func (m *MockPaymentMethodInputPort) DeleteMany(ctx context.Context, ids []string, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMany", ctx, ids, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMany indicates an expected call of DeleteMany.
func (mr *MockPaymentMethodInputPortMockRecorder) DeleteMany(ctx, ids, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockPaymentMethodInputPort)(nil).DeleteMany), ctx, ids, userID)
}

// GetByID mocks base method.
func (m *MockPaymentMethodInputPort) GetByID(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPaymentMethodInputPortMockRecorder) GetByID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPaymentMethodInputPort)(nil).GetByID), ctx, id, userID)
}

// List mocks base method.
func (m *MockPaymentMethodInputPort) List(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockPaymentMethodInputPortMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPaymentMethodInputPort)(nil).List), ctx, userID)
}

// Update mocks base method.
func (m *MockPaymentMethodInputPort) Update(ctx context.Context, id, userID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, userID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPaymentMethodInputPortMockRecorder) Update(ctx, id, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentMethodInputPort)(nil).Update), ctx, id, userID, name)
}

// MockPaymentMethodOutputPort is a mock of PaymentMethodOutputPort interface.
type MockPaymentMethodOutputPort struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentMethodOutputPortMockRecorder
	isgomock struct{}
}

// MockPaymentMethodOutputPortMockRecorder is the mock recorder for MockPaymentMethodOutputPort.
type MockPaymentMethodOutputPortMockRecorder struct {
	mock *MockPaymentMethodOutputPort
}

// NewMockPaymentMethodOutputPort creates a new mock instance.
func NewMockPaymentMethodOutputPort(ctrl *gomock.Controller) *MockPaymentMethodOutputPort {
	mock := &MockPaymentMethodOutputPort{ctrl: ctrl}
	mock.recorder = &MockPaymentMethodOutputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentMethodOutputPort) EXPECT() *MockPaymentMethodOutputPortMockRecorder {
	return m.recorder
}

// PresentPaymentMethod mocks base method.
func (m *MockPaymentMethodOutputPort) PresentPaymentMethod(ctx context.Context, pm *payment_method.PaymentMethod, usageCount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentPaymentMethod", ctx, pm, usageCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// PresentPaymentMethod indicates an expected call of PresentPaymentMethod.
func (mr *MockPaymentMethodOutputPortMockRecorder) PresentPaymentMethod(ctx, pm, usageCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentPaymentMethod", reflect.TypeOf((*MockPaymentMethodOutputPort)(nil).PresentPaymentMethod), ctx, pm, usageCount)
}

// PresentPaymentMethods mocks base method.
func (m *MockPaymentMethodOutputPort) PresentPaymentMethods(ctx context.Context, pms []*port.PaymentMethodWithCount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentPaymentMethods", ctx, pms)
	ret0, _ := ret[0].(error)
	return ret0
}

// PresentPaymentMethods indicates an expected call of PresentPaymentMethods.
func (mr *MockPaymentMethodOutputPortMockRecorder) PresentPaymentMethods(ctx, pms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentPaymentMethods", reflect.TypeOf((*MockPaymentMethodOutputPort)(nil).PresentPaymentMethods), ctx, pms)
}

// MockPaymentMethodRepository is a mock of PaymentMethodRepository interface.
type MockPaymentMethodRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentMethodRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentMethodRepositoryMockRecorder is the mock recorder for MockPaymentMethodRepository.
type MockPaymentMethodRepositoryMockRecorder struct {
	mock *MockPaymentMethodRepository
}

// NewMockPaymentMethodRepository creates a new mock instance.
func NewMockPaymentMethodRepository(ctrl *gomock.Controller) *MockPaymentMethodRepository {
	mock := &MockPaymentMethodRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentMethodRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentMethodRepository) EXPECT() *MockPaymentMethodRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentMethodRepository) Create(ctx context.Context, pm *payment_method.PaymentMethod) (*payment_method.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pm)
	ret0, _ := ret[0].(*payment_method.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPaymentMethodRepositoryMockRecorder) Create(ctx, pm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentMethodRepository)(nil).Create), ctx, pm)
}

// Delete mocks base method.
func (m *MockPaymentMethodRepository) Delete(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPaymentMethodRepositoryMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPaymentMethodRepository)(nil).Delete), ctx, id, userID)
}

// DeleteMany mocks base method.
func (m *MockPaymentMethodRepository) DeleteMany(ctx context.Context, ids []string, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMany", ctx, ids, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMany indicates an expected call of DeleteMany.
func (mr *MockPaymentMethodRepositoryMockRecorder) DeleteMany(ctx, ids, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockPaymentMethodRepository)(nil).DeleteMany), ctx, ids, userID)
}

// FindByID mocks base method.
func (m *MockPaymentMethodRepository) FindByID(ctx context.Context, id, userID string) (*payment_method.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id, userID)
	ret0, _ := ret[0].(*payment_method.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPaymentMethodRepositoryMockRecorder) FindByID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPaymentMethodRepository)(nil).FindByID), ctx, id, userID)
}

// FindByIDs mocks base method.
func (m *MockPaymentMethodRepository) FindByIDs(ctx context.Context, ids []string, userID string) ([]*payment_method.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ctx, ids, userID)
	ret0, _ := ret[0].([]*payment_method.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockPaymentMethodRepositoryMockRecorder) FindByIDs(ctx, ids, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockPaymentMethodRepository)(nil).FindByIDs), ctx, ids, userID)
}

// FindByUserID mocks base method.
func (m *MockPaymentMethodRepository) FindByUserID(ctx context.Context, userID string) ([]*payment_method.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]*payment_method.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockPaymentMethodRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockPaymentMethodRepository)(nil).FindByUserID), ctx, userID)
}

// FindByUserIDWithCount mocks base method.
func (m *MockPaymentMethodRepository) FindByUserIDWithCount(ctx context.Context, userID string) ([]*port.PaymentMethodWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDWithCount", ctx, userID)
	ret0, _ := ret[0].([]*port.PaymentMethodWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDWithCount indicates an expected call of FindByUserIDWithCount.
func (mr *MockPaymentMethodRepositoryMockRecorder) FindByUserIDWithCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDWithCount", reflect.TypeOf((*MockPaymentMethodRepository)(nil).FindByUserIDWithCount), ctx, userID)
}

// Update mocks base method.
func (m *MockPaymentMethodRepository) Update(ctx context.Context, pm *payment_method.PaymentMethod) (*payment_method.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, pm)
	ret0, _ := ret[0].(*payment_method.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPaymentMethodRepositoryMockRecorder) Update(ctx, pm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentMethodRepository)(nil).Update), ctx, pm)
}
