// Code generated by MockGen. DO NOT EDIT.
// Source: subscription_port.go
//
// Generated by this command:
//
//	mockgen -source=subscription_port.go -destination=../usecase/mock/mock_subscription_usecase.go -package=mockusecase
//

// Package mockusecase is a generated GoMock package.
package mockusecase

import (
	context "context"
	reflect "reflect"

	subscription "github.com/atsushi-h/subsq/backend/internal/domain/subscription"
	port "github.com/atsushi-h/subsq/backend/internal/port"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionInputPort is a mock of SubscriptionInputPort interface.
type MockSubscriptionInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionInputPortMockRecorder
	isgomock struct{}
}

// MockSubscriptionInputPortMockRecorder is the mock recorder for MockSubscriptionInputPort.
type MockSubscriptionInputPortMockRecorder struct {
	mock *MockSubscriptionInputPort
}

// NewMockSubscriptionInputPort creates a new mock instance.
func NewMockSubscriptionInputPort(ctrl *gomock.Controller) *MockSubscriptionInputPort {
	mock := &MockSubscriptionInputPort{ctrl: ctrl}
	mock.recorder = &MockSubscriptionInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionInputPort) EXPECT() *MockSubscriptionInputPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubscriptionInputPort) Create(ctx context.Context, userID string, input port.CreateSubscriptionInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSubscriptionInputPortMockRecorder) Create(ctx, userID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubscriptionInputPort)(nil).Create), ctx, userID, input)
}

// Delete mocks base method.
func (m *MockSubscriptionInputPort) Delete(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSubscriptionInputPortMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubscriptionInputPort)(nil).Delete), ctx, id, userID)
}

// DeleteMany mocks base method.
func (m *MockSubscriptionInputPort) DeleteMany(ctx context.Context, ids []string, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMany", ctx, ids, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMany indicates an expected call of DeleteMany.
func (mr *MockSubscriptionInputPortMockRecorder) DeleteMany(ctx, ids, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockSubscriptionInputPort)(nil).DeleteMany), ctx, ids, userID)
}

// Get mocks base method.
func (m *MockSubscriptionInputPort) Get(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockSubscriptionInputPortMockRecorder) Get(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSubscriptionInputPort)(nil).Get), ctx, id, userID)
}

// List mocks base method.
func (m *MockSubscriptionInputPort) List(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockSubscriptionInputPortMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSubscriptionInputPort)(nil).List), ctx, userID)
}

// Update mocks base method.
func (m *MockSubscriptionInputPort) Update(ctx context.Context, id, userID string, input port.UpdateSubscriptionInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, userID, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSubscriptionInputPortMockRecorder) Update(ctx, id, userID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubscriptionInputPort)(nil).Update), ctx, id, userID, input)
}

// MockSubscriptionOutputPort is a mock of SubscriptionOutputPort interface.
type MockSubscriptionOutputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionOutputPortMockRecorder
	isgomock struct{}
}

// MockSubscriptionOutputPortMockRecorder is the mock recorder for MockSubscriptionOutputPort.
type MockSubscriptionOutputPortMockRecorder struct {
	mock *MockSubscriptionOutputPort
}

// NewMockSubscriptionOutputPort creates a new mock instance.
func NewMockSubscriptionOutputPort(ctrl *gomock.Controller) *MockSubscriptionOutputPort {
	mock := &MockSubscriptionOutputPort{ctrl: ctrl}
	mock.recorder = &MockSubscriptionOutputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionOutputPort) EXPECT() *MockSubscriptionOutputPortMockRecorder {
	return m.recorder
}

// PresentSubscription mocks base method.
func (m *MockSubscriptionOutputPort) PresentSubscription(ctx context.Context, sub *subscription.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentSubscription", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// PresentSubscription indicates an expected call of PresentSubscription.
func (mr *MockSubscriptionOutputPortMockRecorder) PresentSubscription(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentSubscription", reflect.TypeOf((*MockSubscriptionOutputPort)(nil).PresentSubscription), ctx, sub)
}

// PresentSubscriptions mocks base method.
func (m *MockSubscriptionOutputPort) PresentSubscriptions(ctx context.Context, subs []*subscription.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentSubscriptions", ctx, subs)
	ret0, _ := ret[0].(error)
	return ret0
}

// PresentSubscriptions indicates an expected call of PresentSubscriptions.
func (mr *MockSubscriptionOutputPortMockRecorder) PresentSubscriptions(ctx, subs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentSubscriptions", reflect.TypeOf((*MockSubscriptionOutputPort)(nil).PresentSubscriptions), ctx, subs)
}

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// CountByPaymentMethodID mocks base method.
func (m *MockSubscriptionRepository) CountByPaymentMethodID(ctx context.Context, pmID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByPaymentMethodID", ctx, pmID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByPaymentMethodID indicates an expected call of CountByPaymentMethodID.
func (mr *MockSubscriptionRepositoryMockRecorder) CountByPaymentMethodID(ctx, pmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByPaymentMethodID", reflect.TypeOf((*MockSubscriptionRepository)(nil).CountByPaymentMethodID), ctx, pmID)
}

// CountByPaymentMethodIDs mocks base method.
func (m *MockSubscriptionRepository) CountByPaymentMethodIDs(ctx context.Context, ids []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByPaymentMethodIDs", ctx, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByPaymentMethodIDs indicates an expected call of CountByPaymentMethodIDs.
func (mr *MockSubscriptionRepositoryMockRecorder) CountByPaymentMethodIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByPaymentMethodIDs", reflect.TypeOf((*MockSubscriptionRepository)(nil).CountByPaymentMethodIDs), ctx, ids)
}

// Create mocks base method.
func (m *MockSubscriptionRepository) Create(ctx context.Context, s *subscription.Subscription) (*subscription.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(*subscription.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSubscriptionRepositoryMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubscriptionRepository)(nil).Create), ctx, s)
}

// Delete mocks base method.
func (m *MockSubscriptionRepository) Delete(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSubscriptionRepositoryMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubscriptionRepository)(nil).Delete), ctx, id, userID)
}

// DeleteMany mocks base method.
func (m *MockSubscriptionRepository) DeleteMany(ctx context.Context, ids []string, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMany", ctx, ids, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMany indicates an expected call of DeleteMany.
func (mr *MockSubscriptionRepositoryMockRecorder) DeleteMany(ctx, ids, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockSubscriptionRepository)(nil).DeleteMany), ctx, ids, userID)
}

// FindByID mocks base method.
func (m *MockSubscriptionRepository) FindByID(ctx context.Context, id, userID string) (*subscription.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id, userID)
	ret0, _ := ret[0].(*subscription.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSubscriptionRepositoryMockRecorder) FindByID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSubscriptionRepository)(nil).FindByID), ctx, id, userID)
}

// FindByIDs mocks base method.
func (m *MockSubscriptionRepository) FindByIDs(ctx context.Context, ids []string, userID string) ([]*subscription.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ctx, ids, userID)
	ret0, _ := ret[0].([]*subscription.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockSubscriptionRepositoryMockRecorder) FindByIDs(ctx, ids, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockSubscriptionRepository)(nil).FindByIDs), ctx, ids, userID)
}

// FindByUserID mocks base method.
func (m *MockSubscriptionRepository) FindByUserID(ctx context.Context, userID string) ([]*subscription.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]*subscription.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockSubscriptionRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockSubscriptionRepository)(nil).FindByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockSubscriptionRepository) Update(ctx context.Context, s *subscription.Subscription) (*subscription.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, s)
	ret0, _ := ret[0].(*subscription.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSubscriptionRepositoryMockRecorder) Update(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubscriptionRepository)(nil).Update), ctx, s)
}
