// Code generated by MockGen. DO NOT EDIT.
// Source: notification_port.go
//
// Generated by this command:
//
//	mockgen -source=notification_port.go -destination=../usecase/mock/mock_notification_usecase.go -package=mockusecase
//

// Package mockusecase is a generated GoMock package.
package mockusecase

import (
	context "context"
	reflect "reflect"

	notification "github.com/atsushi-h/subsq/backend/internal/domain/notification"
	port "github.com/atsushi-h/subsq/backend/internal/port"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationInputPort is a mock of NotificationInputPort interface.
type MockNotificationInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationInputPortMockRecorder
	isgomock struct{}
}

// MockNotificationInputPortMockRecorder is the mock recorder for MockNotificationInputPort.
type MockNotificationInputPortMockRecorder struct {
	mock *MockNotificationInputPort
}

// NewMockNotificationInputPort creates a new mock instance.
func NewMockNotificationInputPort(ctrl *gomock.Controller) *MockNotificationInputPort {
	mock := &MockNotificationInputPort{ctrl: ctrl}
	mock.recorder = &MockNotificationInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationInputPort) EXPECT() *MockNotificationInputPortMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockNotificationInputPort) Broadcast(ctx context.Context, input port.BroadcastInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Broadcast", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockNotificationInputPortMockRecorder) Broadcast(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockNotificationInputPort)(nil).Broadcast), ctx, input)
}

// ListMySubscriptions mocks base method.
func (m *MockNotificationInputPort) ListMySubscriptions(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMySubscriptions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListMySubscriptions indicates an expected call of ListMySubscriptions.
func (mr *MockNotificationInputPortMockRecorder) ListMySubscriptions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMySubscriptions", reflect.TypeOf((*MockNotificationInputPort)(nil).ListMySubscriptions), ctx, userID)
}

// SendTest mocks base method.
func (m *MockNotificationInputPort) SendTest(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTest", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTest indicates an expected call of SendTest.
func (mr *MockNotificationInputPortMockRecorder) SendTest(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTest", reflect.TypeOf((*MockNotificationInputPort)(nil).SendTest), ctx, userID)
}

// Subscribe mocks base method.
func (m *MockNotificationInputPort) Subscribe(ctx context.Context, userID string, input port.SubscribeInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, userID, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockNotificationInputPortMockRecorder) Subscribe(ctx, userID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockNotificationInputPort)(nil).Subscribe), ctx, userID, input)
}

// Unsubscribe mocks base method.
func (m *MockNotificationInputPort) Unsubscribe(ctx context.Context, userID, endpoint string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", ctx, userID, endpoint)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockNotificationInputPortMockRecorder) Unsubscribe(ctx, userID, endpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockNotificationInputPort)(nil).Unsubscribe), ctx, userID, endpoint)
}

// MockNotificationOutputPort is a mock of NotificationOutputPort interface.
type MockNotificationOutputPort struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationOutputPortMockRecorder
	isgomock struct{}
}

// MockNotificationOutputPortMockRecorder is the mock recorder for MockNotificationOutputPort.
type MockNotificationOutputPortMockRecorder struct {
	mock *MockNotificationOutputPort
}

// NewMockNotificationOutputPort creates a new mock instance.
func NewMockNotificationOutputPort(ctrl *gomock.Controller) *MockNotificationOutputPort {
	mock := &MockNotificationOutputPort{ctrl: ctrl}
	mock.recorder = &MockNotificationOutputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationOutputPort) EXPECT() *MockNotificationOutputPortMockRecorder {
	return m.recorder
}

// PresentPushSubscriptions mocks base method.
func (m *MockNotificationOutputPort) PresentPushSubscriptions(ctx context.Context, subs []*notification.PushSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentPushSubscriptions", ctx, subs)
	ret0, _ := ret[0].(error)
	return ret0
}

// PresentPushSubscriptions indicates an expected call of PresentPushSubscriptions.
func (mr *MockNotificationOutputPortMockRecorder) PresentPushSubscriptions(ctx, subs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentPushSubscriptions", reflect.TypeOf((*MockNotificationOutputPort)(nil).PresentPushSubscriptions), ctx, subs)
}

// PresentSinglePushSubscription mocks base method.
func (m *MockNotificationOutputPort) PresentSinglePushSubscription(ctx context.Context, sub *notification.PushSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentSinglePushSubscription", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// PresentSinglePushSubscription indicates an expected call of PresentSinglePushSubscription.
func (mr *MockNotificationOutputPortMockRecorder) PresentSinglePushSubscription(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentSinglePushSubscription", reflect.TypeOf((*MockNotificationOutputPort)(nil).PresentSinglePushSubscription), ctx, sub)
}

// MockPushSubscriptionRepository is a mock of PushSubscriptionRepository interface.
type MockPushSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPushSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockPushSubscriptionRepositoryMockRecorder is the mock recorder for MockPushSubscriptionRepository.
type MockPushSubscriptionRepositoryMockRecorder struct {
	mock *MockPushSubscriptionRepository
}

// NewMockPushSubscriptionRepository creates a new mock instance.
func NewMockPushSubscriptionRepository(ctrl *gomock.Controller) *MockPushSubscriptionRepository {
	mock := &MockPushSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockPushSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushSubscriptionRepository) EXPECT() *MockPushSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// DeleteByEndpoint mocks base method.
func (m *MockPushSubscriptionRepository) DeleteByEndpoint(ctx context.Context, endpoint, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByEndpoint", ctx, endpoint, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByEndpoint indicates an expected call of DeleteByEndpoint.
func (mr *MockPushSubscriptionRepositoryMockRecorder) DeleteByEndpoint(ctx, endpoint, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByEndpoint", reflect.TypeOf((*MockPushSubscriptionRepository)(nil).DeleteByEndpoint), ctx, endpoint, userID)
}

// DeleteByID mocks base method.
func (m *MockPushSubscriptionRepository) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockPushSubscriptionRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockPushSubscriptionRepository)(nil).DeleteByID), ctx, id)
}

// FindAll mocks base method.
func (m *MockPushSubscriptionRepository) FindAll(ctx context.Context) ([]*notification.PushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*notification.PushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPushSubscriptionRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPushSubscriptionRepository)(nil).FindAll), ctx)
}

// FindByUserID mocks base method.
func (m *MockPushSubscriptionRepository) FindByUserID(ctx context.Context, userID string) ([]*notification.PushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]*notification.PushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockPushSubscriptionRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockPushSubscriptionRepository)(nil).FindByUserID), ctx, userID)
}

// Upsert mocks base method.
func (m *MockPushSubscriptionRepository) Upsert(ctx context.Context, sub *notification.PushSubscription) (*notification.PushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, sub)
	ret0, _ := ret[0].(*notification.PushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockPushSubscriptionRepositoryMockRecorder) Upsert(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockPushSubscriptionRepository)(nil).Upsert), ctx, sub)
}

// MockWebPushSender is a mock of WebPushSender interface.
type MockWebPushSender struct {
	ctrl     *gomock.Controller
	recorder *MockWebPushSenderMockRecorder
	isgomock struct{}
}

// MockWebPushSenderMockRecorder is the mock recorder for MockWebPushSender.
type MockWebPushSenderMockRecorder struct {
	mock *MockWebPushSender
}

// NewMockWebPushSender creates a new mock instance.
func NewMockWebPushSender(ctrl *gomock.Controller) *MockWebPushSender {
	mock := &MockWebPushSender{ctrl: ctrl}
	mock.recorder = &MockWebPushSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebPushSender) EXPECT() *MockWebPushSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockWebPushSender) Send(ctx context.Context, endpoint, p256dh, auth string, payload []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, endpoint, p256dh, auth, payload)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockWebPushSenderMockRecorder) Send(ctx, endpoint, p256dh, auth, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockWebPushSender)(nil).Send), ctx, endpoint, p256dh, auth, payload)
}
